<a href="https://colab.research.google.com/github/karanveer-sharma/localrepo/blob/main/pandasbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:

data_dict = {'a' : 100, 'b' : 200, 'c':300}
series_dict = pd.Series(data_dict)
print("series from dict\n", series_dict)

series from dict
 a    100
b    200
c    300
dtype: int64

In [ ]:
data = {
    'roll no':[10, 20, 30, 40,],
    'name': ['karan', 'dhruv','japjeet','harman'],
    'department':['cse','ece', 'mech','architecture']
}
df = pd.DataFrame(data)
print("student DataFrame")
display(df)

student DataFrame

   roll no     name    department
0       10    karan           cse
1       20    dhruv           ece
2       30  japjeet          mech
3       40   harman  architecture

In [ ]:
print("first 3 rows :")
print(df.head(2))
print(df.tail(2))

first 3 rows :
   roll no   name department
0       10  karan        cse
1       20  dhruv        ece
   roll no     name    department
2       30  japjeet          mech
3       40   harman  architecture

In [ ]:
print("\nRandom Sample")
display(df.sample(2))

Random Sample

   roll no   name department
0       10  karan        cse
1       20  dhruv        ece

In [ ]:
print("dataframe info :")
print(df.info())

dataframe info :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   roll no     4 non-null      int64
 1   name        4 non-null      object
 2   department  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes
None

In [ ]:
print("\nShape of Data :", df.shape[0])

Shape of Data : 4

In [ ]:
print("\nShape of Data :", df.shape)

Shape of Data : (4, 3)

In [ ]:
print("\nDatatypes :\n", df.dtypes)

Datatypes :
 roll no        int64
name          object
department    object
dtype: object

In [ ]:
print("Stastical Summary")
display(df.describe(include='all'))

Stastical Summary

          roll no   name department
count    4.000000      4          4
unique        NaN      4          4
top           NaN  karan        cse
freq          NaN      1          1
mean    25.000000    NaN        NaN
std     12.909944    NaN        NaN
min     10.000000    NaN        NaN
25%     17.500000    NaN        NaN
50%     25.000000    NaN        NaN
75%     32.500000    NaN        NaN
max     40.000000    NaN        NaN

In [ ]:
names=df["name"]
print("Names column :\n", names)

Names column :
 0      karan
1      dhruv
2    japjeet
3     harman
Name: name, dtype: object

In [ ]:
att =df["department"]
print("departments\n", att)

departments
 0             cse
1             ece
2            mech
3    architecture
Name: department, dtype: object

In [ ]:
subset=df[["name","department"]]
print(subset)

      name    department
0    karan           cse
1    dhruv           ece
2  japjeet          mech
3   harman  architecture

In [ ]:
df_index= df.set_index("roll no")
print(df_index)
display(df)

            name    department
roll no
10         karan           cse
20         dhruv           ece
30       japjeet          mech
40        harman  architecture

   roll no     name    department
0       10    karan           cse
1       20    dhruv           ece
2       30  japjeet          mech
3       40   harman  architecture

In [ ]:
student_20= df_index.loc[20]
print(student_20)
print(student_20["department"])

name          dhruv
department      ece
Name: 20, dtype: object
ece

In [ ]:
row_1=df_index.iloc[1]
print(row_1)
slice_data= df_index.iloc[0:2][0:3]
print(slice_data)

name          dhruv
department      ece
Name: 20, dtype: object
          name department
roll no
10       karan        cse
20       dhruv        ece

In [ ]:
print(np.arange(0,10,100))
print(np.linspace(0,10,50))

[0]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

In [ ]:
high_scorers=df[df["name"]== "karan"]
print(high_scorers)

   roll no   name department
0       10  karan        cse

In [ ]:
cse_a=df[(df["department"]=="cse") & (df["name"]== "karan")]
print(cse_a)

   roll no   name department
0       10  karan        cse

In [ ]:
print(df.isnull().sum())

roll no       0
name          0
department    0
dtype: int64

In [ ]:
df_clean=df.dropna()
print(df_clean)

   roll no     name    department
0       10    karan           cse
1       20    dhruv           ece
2       30  japjeet          mech
3       40   harman  architecture

In [ ]:
mean_roll=df["roll no"].mean()
df_fill=df.copy()
df_fill["roll no"] = df_fill["roll no"].fillna(mean_roll)
print(df_fill)

   roll no     name    department
0       10    karan           cse
1       20    dhruv           ece
2       30  japjeet          mech
3       40   harman  architecture